2022-08-21 15:17:36,751 : INFO : root : Loading config.
2022-08-21 15:17:37,265 : INFO : ConfigProcessor : Config spec file cache created: C:\Users\Brendan\AppData\Local\Temp\config_spec.mpf_cache
2022-08-21 15:17:37,265 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2022-08-21 15:17:37,266 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Brendan\AppData\Local\Temp\bccefe987bb586eace29905fa80cab57.mpf_cache
2022-08-21 15:17:37,320 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Brendan\AppData\Local\Temp\467e7647689d29fad6adf949e1f4d51d.mpf_cache
2022-08-21 15:17:37,321 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Brendan\AppData\Local\Temp\5550e037aa776b42b91b29b40b356c70.mpf_cache
2022-08-21 15:17:37,322 : WARNING : ConfigProcessor : Config file in cache changed: C:\Baby_pacman_code\machine\modes\base\config\base.yaml
2022-08-21 15:17:37,322 : INFO : ConfigProcessor : Loading config from file C:\Baby_pacman_code\machine\modes\base\config\base.yaml.
2022-08-21 15:17:37,436 : INFO : ConfigProcessor : Loading config: C:\Baby_pacman_code\machine\modes\base\config\base.yaml
2022-08-21 15:18:53,296 : ERROR : root : Shutdown because of SIGINT or keyboard interrupt.
Traceback (most recent call last):
  File "c:\users\brendan\appdata\local\programs\python\python37\lib\site-packages\mpf\commands\game.py", line 230, in __init__
    config = config_loader.load_mpf_config()
  File "c:\users\brendan\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_loader.py", line 155, in load_mpf_config
    mode_config = self._load_modes(config_spec, machine_config)
  File "c:\users\brendan\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_loader.py", line 218, in _load_modes
    ignore_unknown_sections=ignore_unknown_sections)
  File "c:\users\brendan\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_processor.py", line 125, in load_config_files_with_cache
    config_spec=config_spec)
  File "c:\users\brendan\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_processor.py", line 191, in _load_config_file_and_return_loaded_files
    self._check_sections(config_spec, config, config_type, filename, ignore_unknown_sections)
  File "c:\users\brendan\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_processor.py", line 164, in _check_sections
    2, self.log.name, filename)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigProcessor: Found a "player_vars:" section in config file C:\Baby_pacman_code\machine\modes\base\config\base.yaml, but that section is not valid in mode config files (only in machine). Context: C:\Baby_pacman_code\machine\modes\base\config\base.yaml Error Code: CFE-ConfigProcessor-2 (https://docs.missionpinball.org/en/0.55/logs/CFE-ConfigProcessor-2.html)
